# Generated by Django 5.0.4 on 2024-04-12 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='completion_time',
            field=models.DateField(blank=True, null=True, verbose_name='Completion Time'),
        ),
    ]
